.MODEL SMALL
.STACK 100H

.DATA
MSGU DB 13,10,'UPPERCASE LETTER$'
MSGL DB 13,10,'LOWERCASE LETTER$'
MSGD DB 13,10,'DIGIT$'
MSGS DB 13,10,'SPECIAL CHARACTER$'

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    ; READ CHARACTER
    MOV AH, 01H
    INT 21H
    MOV BL, AL

    ; CHECK UPPERCASE A–Z
    CMP BL, 'A'
    JB CHECK_LOWER
    CMP BL, 'Z'
    JA CHECK_LOWER
    LEA DX, MSGU
    JMP DISPLAY

CHECK_LOWER:
    ; CHECK LOWERCASE a–z
    CMP BL, 'a'
    JB CHECK_DIGIT
    CMP BL, 'z'
    JA CHECK_DIGIT
    LEA DX, MSGL
    JMP DISPLAY

CHECK_DIGIT:
    ; CHECK DIGIT 0–9
    CMP BL, '0'
    JB SPECIAL
    CMP BL, '9'
    JA SPECIAL
    LEA DX, MSGD
    JMP DISPLAY

SPECIAL:
    LEA DX, MSGS

DISPLAY:
    MOV AH, 09H
    INT 21H

    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN