.MODEL SMALL
.STACK 100H
.DATA
NAMEMSG DB "YOUR NAME: MR. JOHN", 0DH, 0AH, '$'
NUMMSG1 DB "YOUR First NUMBER is: ", '$'
NUMMSG2 DB "YOUR SECOND NUMBER is: ", '$'
SUMMSG DB "SUM OF DIGITS: ", '$'
SUBMSG DB "SUB OF DIGITS: ", '$'
NEWLINE DB 0DH, 0AH, '$'
DIGIT1 DB 5
DIGIT2 DB 4
.CODE
MAIN PROC
MOV AX, @DATA
MOV DS, AX
LEA DX, NAMEMSG
MOV AH, 09H
INT 21H
LEA DX, NUMMSG1
MOV AH, 09H
INT 21H
MOV AL, DIGIT1
ADD AL, '0'
MOV DL, AL
MOV AH, 02H
INT 21H
LEA DX, NEWLINE
MOV AH, 09H
INT 21H
LEA DX, NUMMSG2
MOV AH, 09H
INT 21H
MOV AL, DIGIT2
ADD AL, '0'
MOV DL, AL
MOV AH, 02H
INT 21H
LEA DX, NEWLINE
MOV AH, 09H
INT 21H
LEA DX, SUMMSG
MOV AH, 09H
INT 21H
MOV AL, DIGIT1
ADD AL, DIGIT2
ADD AL, '0'
MOV DL, AL
MOV AH, 02H
INT 21H
LEA DX, NEWLINE
MOV AH, 09H
INT 21H
LEA DX, SUBMSG
MOV AH, 09H
INT 21H
MOV AL, DIGIT1
SUB AL, DIGIT2
ADD AL, '0'
MOV DL, AL
MOV AH, 02H
INT 21H
MOV AH, 4CH
INT 21H
MAIN ENDP
END MAIN